ACCESS_MANAGER_CONF = {'regionAndCfg': {'ap-southeast-1': {'securityGrpIds': ['sg-5f75ea38', 'sg-08fe0e8b087deda8d']},
                  'eu-west-1': {'securityGrpIds': ['sg-02497be4d4185c6ab']},
                  'ap-south-1': {'securityGrpIds': ['sg-0d0cadf3e794764bd', 'sg-00e295a20e41f33a3']},
                  'ap-south-2': {'securityGrpIds': ['sg-000fd95c8c0e403e3']}},
 'OTP_PREFIX': '',
 'OTP_VALID_FOR_SECS': 300,
 'SMS_LANE_URL_PARAMS': {'user': '', 'password': '', 'msisdn': None, 'sid': '', 'msg': None, 'fl': 0, 'gwid': 2},
 'webAccessConfig': {'logAccess': '/home/django-app/Naveena/allowed_ip_list.conf',
                     'metricAccess': '/home/django-app/Naveena/SERVERMETRICS_allowed_ip_list.conf'},
 'hpAgentAccessConfig': {'region': 'ap-southeast-1', 'securityGrpId': 'sg-08b9d8fe8c4eecacb', 'ports': [22]},
 'ALLOWED_USR_IDENTITIES': {'naveena': {'password': '',
                                        'otpSeed': '',
                                        'portsToOpen': [22],
                                        'allowLogAccess': True,
                                        'allowHpAgentAccess': True,
                                        'allowServerMetricsAccess': True},
                            'naveen.adhikari': {'password': '',
                                                'otpSeed': '',
                                                'allowLogAccess': True,
                                                'allowHpAgentAccess': True,
                                                'allowServerMetricsAccess': True},
                            'elangovan': {'mobile': '',
                                          'password': '',
                                          'otpSeed': '',
                                          'allowLogAccess': True,
                                          'allowHpAgentAccess': True,
                                          'overRiddenRegionAndCfg': {'ap-south-1': {'securityGrpIds': ['sg-11684d78',
                                                                                                       'sg-0c6d2ff75555c6b78',
                                                                                                       'sg-0d0cadf3e794764bd',
                                                                                                       'sg-00e295a20e41f33a3'],
                                                                                    'portsToOpen': [22, 3306]},
                                                                     'ap-southeast-1': {'securityGrpIds': ['sg-08fe0e8b087deda8d'],
                                                                                        'portsToOpen': [22]},
                                                                     'eu-west-1': {'securityGrpIds': ['sg-02497be4d4185c6ab'],
                                                                                   'portsToOpen': [22, 3306]},
                                                                     'ap-south-2': {'portsToOpen': [22, 3306],
                                                                                    'securityGrpIds': ['sg-000fd95c8c0e403e3']}}},
                            'naveen': {'password': '$2b$12$vLGLIInTbI76JUnsjKoncOhoiH1bdriWHzf1cpVrJLlWx/x8nQxYG',
                                       'otpSeed': 'LXDN5DOLECKQ4YWIQBUV6FGIJWB6ZNJW',
                                       'allowLogAccess': True,
                                       'allowHpAgentAccess': True,
                                       'allowServerMetricsAccess': True,
                                       'portsToOpen': [22, 1890]},
                            'proxima': {'password': '$2b$12$M5OCimnaHNN9CqnBxEGq1.10xe4GBvza5cKTNl9bVRyrn0K2uk.mC',
                                        'otpSeed': 'LXDN5DOLECKQ4YWIQBUV6FGIJWB6ZNJW',
                                        'allowLogAccess': True,
                                        'allowHpAgentAccess': True,
                                        'allowServerMetricsAccess': True,
                                        'portsToOpen': [22]},
                          
}}
